import type { Metadata } from "next";
import { getProductData } from "@/lib/admin/product";

export const metadata: Metadata = { title: "Product | Auterim Admin", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

const number = (value: number | null) => value === null ? "Unavailable" : value.toLocaleString("en-US");
const label = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
// A lag figure that was never measured stays "Not measured". It is never
// rendered as a reassuring zero.
const lagAge = (minutes: number | null) => minutes === null ? "Not measured" : minutes < 60 ? `${minutes}m` : `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
const connectorList = (keys: string[]) => keys.length ? keys.map(label).join(", ") : "None";

function Metric({ label: title, value, note }: { label: string; value: string; note: string }) {
  return <article className="admin-kpi"><div className="admin-eyebrow">{title}</div><div className={`admin-kpi-value${value === "Unavailable" ? " unavailable" : ""}`}>{value}</div><div className="admin-kpi-note">{note}</div></article>;
}

export default async function ProductPage() {
  const data = await getProductData();
  const tone = data.sourceStatus === "connected" ? "live" : data.sourceStatus === "partial" ? "partial" : "offline";

  return <div className="admin-command-center admin-detail-page">
    <div className="admin-page-intro"><div><div className="admin-kicker"><span className={`admin-status-dot ${tone}`} />Auterim / product</div><h1>Work in motion.</h1><p>Operational product health from operator runtime, human approvals, and connector readiness.</p></div><div className="admin-intro-meta"><span className={`admin-status-pill ${tone}`}>{data.sourceStatus === "connected" ? "Product sources live" : data.sourceStatus === "partial" ? "Partial product data" : "Sources unavailable"}</span><span>Last 500 records per source</span></div></div>
    <section className="admin-kpi-grid admin-kpi-grid-four"><Metric label="Operator runs" value={number(data.runs.total)} note="Recent runtime records" /><Metric label="Completed" value={number(data.runs.completed)} note="Completed or succeeded runs" /><Metric label="Awaiting work" value={number(data.runs.running)} note="Running, queued, or pending runs" /><Metric label="Failed" value={number(data.runs.failed)} note="Failed, errored, or canceled runs" /></section>
    {data.unavailable ? <section className="admin-panel"><div className="admin-empty-compact">{data.unavailable}</div></section> : <><div className="admin-grid-main"><section className="admin-panel"><div className="admin-panel-head"><div className="admin-eyebrow">Human control</div><h2>Approval state</h2></div><div className="admin-detail-signal-list"><div><span>Pending</span><strong>{number(data.approvals.pending)}</strong></div><div><span>Approved</span><strong>{number(data.approvals.approved)}</strong></div><div><span>Rejected</span><strong>{number(data.approvals.rejected)}</strong></div></div>{data.approvalStates.length ? <div className="admin-detail-tags">{data.approvalStates.map((item) => <span key={item.state}>{label(item.state)} <b>{item.count}</b></span>)}</div> : null}</section><section className="admin-panel"><div className="admin-panel-head"><div className="admin-eyebrow">Connector readiness</div><h2>Systems available to work</h2></div><div className="admin-detail-signal-list"><div><span>Connected systems</span><strong>{number(data.connectors.connected)}</strong></div><div><span>Need attention</span><strong className={data.connectors.needsAttention ? "warning" : ""}>{number(data.connectors.needsAttention)}</strong></div><div><span>Workspaces connected</span><strong>{number(data.connectors.workspaces)}</strong></div></div></section></div><div className="admin-grid-main"><section className="admin-panel"><div className="admin-panel-head"><div className="admin-eyebrow">Operator runtime</div><h2>Work by operator</h2></div>{data.operators.length ? <div className="admin-detail-table admin-detail-table-operators">{data.operators.map((operator) => <div key={operator.key}><div><strong>{label(operator.key)}</strong><small>Operator</small></div><span><small>Total runs</small>{operator.total.toLocaleString()}</span><span><small>Completed</small>{operator.completed.toLocaleString()}</span><span><small>Failed</small><b className={operator.failed ? "admin-detail-state warning" : "admin-detail-state"}>{operator.failed.toLocaleString()}</b></span></div>)}</div> : <div className="admin-empty-compact">No operator runtime records are available.</div>}</section><section className="admin-panel"><div className="admin-panel-head"><div className="admin-eyebrow">Connector mix</div><h2>Recorded connection state</h2></div>{data.connectorStates.length ? <div className="admin-detail-tags admin-detail-tags-stack">{data.connectorStates.map((item) => <span key={`${item.key}-${item.status}`}><i className={`admin-status-dot ${item.status === "connected" ? "live" : ""}`} />{label(item.key)} <small>{label(item.status)}</small><b>{item.count}</b></span>)}</div> : <div className="admin-empty-compact">No connector records are available.</div>}</section></div><div className="admin-grid-main">
      <section className="admin-panel"><div className="admin-panel-head"><div className="admin-eyebrow">Provider reliability</div><h2>What is failing right now</h2></div>{data.operations.providerFailuresAvailable ? <div className="admin-detail-signal-list"><div><span>Recent provider failures</span><strong className={data.operations.recentProviderFailures ? "warning" : ""}>{number(data.operations.recentProviderFailures)}</strong></div><div><span>Degraded</span><strong>{connectorList(data.operations.degradedConnectors)}</strong></div><div><span>Reconnect required</span><strong className={data.operations.reconnectRequiredConnectors.length ? "warning" : ""}>{connectorList(data.operations.reconnectRequiredConnectors)}</strong></div><div><span>Permission required</span><strong>{connectorList(data.operations.permissionRequiredConnectors)}</strong></div><div><span>Rate limited (1h)</span><strong>{connectorList(data.operations.rateLimitedConnectors)}</strong></div></div> : <div className="admin-empty-compact">Provider operation records are not available in the current database.</div>}</section>
      <section className="admin-panel"><div className="admin-panel-head"><div className="admin-eyebrow">Pipeline lag</div><h2>What is backing up</h2></div>{data.operations.lag.available ? <div className="admin-detail-signal-list"><div><span>Signal candidates pending</span><strong>{number(data.operations.lag.signals.pending)}<small> · oldest {lagAge(data.operations.lag.signals.oldestCandidateAgeMinutes)}</small></strong></div><div><span>Workflow steps pending</span><strong>{number(data.operations.lag.workflows.pending)}<small> · oldest {lagAge(data.operations.lag.workflows.oldestAgeMinutes)}</small></strong></div><div><span>Stuck steps</span><strong className={data.operations.lag.workflows.stuck ? "warning" : ""}>{number(data.operations.lag.workflows.stuck)}<small> · oldest {lagAge(data.operations.lag.workflows.oldestStuckAgeMinutes)}</small></strong></div><div><span>Blocked / execution unknown</span><strong>{number(data.operations.lag.workflows.blocked)} / {number(data.operations.lag.workflows.executionUnknown)}</strong></div><div><span>Approvals pending</span><strong>{number(data.operations.lag.approvals.pending)}<small> · oldest {lagAge(data.operations.lag.approvals.oldestAgeMinutes)}</small></strong></div><div><span>Awaiting outcome observation</span><strong>{number(data.operations.lag.outcomeObservation.pending)}<small> · oldest {lagAge(data.operations.lag.outcomeObservation.oldestAgeMinutes)}</small></strong></div></div> : <div className="admin-empty-compact">Pipeline state is not available in the current database.</div>}</section>
    </div></>}
  </div>;
}
