"use client";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useOS } from "@/lib/os/app-provider";
import type { OnboardingState } from "@/lib/os/types";
import { completeOnboardingAction, getOnboardingDraftAction, saveOnboardingDraftAction, type OnboardingDraft } from "./actions";
import "./styles-onboarding.css";

type Priority = Exclude<OnboardingDraft["priority"], "">;
const priorities: Record<Priority, { n: string; title: string; operator: string; avatar: string; description: string; boundary: string }> = {
  revenue: { n: "01", title: "New leads", operator: "Revenue Operator", avatar: "/operators/revenue-operator.png", description: "Qualify new demand and prepare the next reply before a lead waits.", boundary: "External replies and commercial changes remain approval-controlled." },
  client_flow: { n: "02", title: "Client handoffs", operator: "Client Flow Operator", avatar: "/operators/client-flow-operator.png", description: "Prepare onboarding updates, handoffs and follow-ups with the right context.", boundary: "Client-facing commitments remain behind approval where required." },
  operations: { n: "03", title: "Operations", operator: "Operations Operator", avatar: "/operators/operations-operator.png", description: "Surface stalled work and prepare the internal next step before it becomes a delay.", boundary: "Sensitive or company-wide actions stay controlled." },
};
const connectors = [{ id: "gmail", name: "Gmail", mark: "G", color: "#EA4335", note: "Customer conversations and follow-up" }, { id: "hubspot", name: "HubSpot", mark: "Hs", color: "#FF7A59", note: "Contacts, deals and pipeline context" }, { id: "slack", name: "Slack", mark: "Sl", color: "#A77FBC", note: "Internal coordination and decisions" }, { id: "trello", name: "Trello", mark: "Tr", color: "#4BA3E8", note: "Tasks, boards and delivery status" }];
const labels = ["YOUR WORKSPACE", "YOUR BUSINESS", "FIRST OPERATOR", "YOUR SYSTEMS", "READY TO ACTIVATE"];
const blank: OnboardingDraft = { fullName: "", workspaceName: "", websiteUrl: "", industry: "", teamSize: "", priority: "", systems: [], step: 1 };
function normalizedWebsite(value: string) { const text = value.trim(); return !text ? "" : /^https?:\/\//i.test(text) ? text : `https://${text}`; }

export default function OnboardingPage() {
  const router = useRouter(); const { completeOnboarding } = useOS();
  const [draft, setDraft] = useState<OnboardingDraft>(blank); const [ready, setReady] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const submitting = useRef(false);
  useEffect(() => { getOnboardingDraftAction().then((result) => { if (result.ok) setDraft(result.draft); else setError(result.error); setReady(true); }); }, []);
  const update = (patch: Partial<OnboardingDraft>) => setDraft((current) => ({ ...current, ...patch }));
  const choice = draft.priority ? priorities[draft.priority] : null;
  const valid = () => draft.step === 1 ? Boolean(draft.fullName.trim() && draft.workspaceName.trim()) : draft.step === 2 ? Boolean(draft.industry.trim() && draft.teamSize) : draft.step === 3 ? Boolean(draft.priority) : true;
  async function continueStep() { if (!valid()) { setError(draft.step === 1 ? "Add your name and workspace name to continue." : draft.step === 2 ? "Choose an industry and team size to continue." : "Choose the first priority for your team."); return; } setError(""); setBusy(true); const next = Math.min(5, draft.step + 1); const result = await saveOnboardingDraftAction({ ...draft, websiteUrl: normalizedWebsite(draft.websiteUrl), step: next }); setBusy(false); if (!result.ok) return setError(result.error); update({ step: next, websiteUrl: normalizedWebsite(draft.websiteUrl) }); }
  async function activate() { if (submitting.current) return; submitting.current = true; setBusy(true); setError(""); const result = await completeOnboardingAction({ ...draft, websiteUrl: normalizedWebsite(draft.websiteUrl), step: 5 }); if (!result.ok) { setError(result.error); setBusy(false); submitting.current = false; return; } const selected = priorities[draft.priority as Priority]; completeOnboarding({ companyName: draft.workspaceName, websiteUrl: normalizedWebsite(draft.websiteUrl), companySize: draft.teamSize, industry: draft.industry, mainGoals: [selected.title], preferredOperator: selected.operator, preferredDemoPath: draft.priority as NonNullable<OnboardingState["preferredDemoPath"]>, safetyMode: "safe", approvalOwner: result.ownerEmail, initialConnectors: [] }); router.replace("/activate?first=1"); }
  const back = () => { if (draft.step > 1) update({ step: draft.step - 1 }); };
  if (!ready) return <div className="onboarding-shell onboarding-loading">Preparing your operating profile…</div>;
  return <div className="onboarding-shell">
    <header className="onboarding-header"><div className="onboarding-brand"><Image src="/brand/auterim-mark-live.svg" alt="" width={22} height={22} priority /><span>AUTERIM</span><span>/ operating profile</span></div><div className="onboarding-progress"><span>{labels[draft.step - 1]}</span><i><b style={{ width: `${draft.step * 20}%` }} /></i><em>{String(draft.step).padStart(2, "0")} / 05</em></div><button type="button" onClick={() => router.push("/")}>Exit</button></header>
    <main className={`onboarding-main step-${draft.step}`}>
      <section className="onboarding-content"><p className="onboarding-kicker"><i /> {labels[draft.step - 1]}</p>
        {draft.step === 1 && <><h1>Set up your workspace.</h1><p className="onboarding-lead">A clear owner and workspace give every operator the right place to begin.</p><div className="onboarding-fields"><label>YOUR NAME<input value={draft.fullName} onChange={(e) => update({ fullName: e.target.value })} autoComplete="name" /></label><label>WORKSPACE NAME<input value={draft.workspaceName} onChange={(e) => update({ workspaceName: e.target.value })} autoComplete="organization" /></label></div></>}
        {draft.step === 2 && <><h1>Give Auterim the business context that matters.</h1><p className="onboarding-lead">Enough context to make the first recommendation specific. Nothing more.</p><div className="onboarding-fields"><label>WEBSITE <small>OPTIONAL</small><input value={draft.websiteUrl} onChange={(e) => update({ websiteUrl: e.target.value })} placeholder="yourcompany.com" inputMode="url" autoComplete="url" /></label><label>INDUSTRY<input value={draft.industry} onChange={(e) => update({ industry: e.target.value })} placeholder="e.g. Professional services" /></label></div><div className="team-size"><span>TEAM SIZE</span>{["1–5", "6–20", "21–50", "51–200", "200+"].map((size) => <button key={size} type="button" onClick={() => update({ teamSize: size })} className={draft.teamSize === size ? "selected" : ""}>{size}</button>)}</div></>}
        {draft.step === 3 && <><h1>What should Auterim take off your team&apos;s plate first?</h1><p className="onboarding-lead">Choose one operating problem—not an agent. Auterim will prepare the right first operator.</p><div className="priority-list" role="radiogroup">{(Object.keys(priorities) as Priority[]).map((key) => { const item = priorities[key]; const selected = draft.priority === key; return <button key={key} role="radio" aria-checked={selected} className={selected ? "selected" : ""} type="button" onClick={() => update({ priority: key })}><b>{item.n}</b><span><strong>{item.title}</strong><small>{item.description}</small></span><i /></button>; })}</div></>}
        {draft.step === 4 && <><h1>Where does your team already work?</h1><p className="onboarding-lead">Choose the systems your team uses. Nothing is connected to Auterim yet.</p><div className="connector-grid">{connectors.map((item) => { const selected = draft.systems.includes(item.id); return <button type="button" key={item.id} className={selected ? "selected" : ""} onClick={() => update({ systems: selected ? draft.systems.filter((id) => id !== item.id) : [...draft.systems, item.id] })}><b style={{ color: item.color }}>{item.mark}</b><span><strong>{item.name}</strong><small>{item.note}</small></span><i /></button>; })}</div><p className="onboarding-note">Selected means used by your company. You decide what to connect after activation.</p></>}
        {draft.step === 5 && choice && <><h1>Your first operating profile is ready.</h1><p className="onboarding-lead">You can refine this at any time. Your control boundary starts safe.</p><div className="review-grid"><div><span>WORKSPACE</span><b>{draft.workspaceName}</b></div><div><span>COMPANY</span><b>{draft.industry} · {draft.teamSize}</b></div><div><span>WEBSITE</span><b>{draft.websiteUrl || "Not provided"}</b></div><div><span>FIRST PRIORITY</span><b>{choice.title}</b></div><div><span>RECOMMENDED OPERATOR</span><b>{choice.operator}</b></div><div><span>RELEVANT SYSTEMS</span><b>{draft.systems.length ? draft.systems.map((id) => connectors.find((item) => item.id === id)?.name).join(" · ") : "Not provided"}</b></div></div><p className="control-boundary"><i /> {choice.boundary}</p></>}
        {error && <p className="onboarding-error" role="alert">{error}</p>}
      </section>
      {(draft.step === 3 || draft.step === 5) && choice && <aside className="operator-recommendation"><div><span>RECOMMENDED OPERATOR</span><b><i /> READY</b></div><section><figure><Image src={choice.avatar} alt="" width={112} height={112} /></figure><p><span>{choice.title.toUpperCase()} / FIRST LANE</span><strong>{choice.operator}</strong><small>{choice.description}</small></p></section><footer><i /> {choice.boundary}</footer></aside>}
    </main>
    <footer className="onboarding-footer"><span><i /> APPROVALS ARE ON BY DEFAULT</span><p>{draft.step === 4 ? "Select systems now, connect only when there is a clear reason." : "Prepared work is allowed. Sensitive actions wait for your approval."}</p><div>{draft.step > 1 && <button type="button" className="back" onClick={back} disabled={busy}>Back</button>}{draft.step === 4 && <button type="button" className="skip" onClick={continueStep} disabled={busy}>Skip for now</button>}<button type="button" className="primary" onClick={draft.step === 5 ? activate : continueStep} disabled={busy}>{busy ? "Saving…" : draft.step === 5 ? "Activate workspace →" : "Continue →"}</button></div></footer>
  </div>;
}
