import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const migration = read("supabase/migrations/20260907_os_notifications.sql");
const source = read("src/lib/notifications/workspace-notifications.ts");
const route = read("src/app/api/notifications/route.ts");
const center = read("src/components/dashboard/notification-center.tsx");
const topbar = read("src/components/dashboard/topbar.tsx");
const navigation = read("src/lib/app-navigation.ts");

assert.match(migration, /create table if not exists public\.os_notifications/);
assert.match(migration, /unique \(workspace_id, dedupe_key\)/, "active source issues are deduplicated per workspace");
assert.match(migration, /enable row level security/, "notification state is RLS-protected");
assert.match(migration, /read_at/);
assert.match(migration, /dismissed_at/);
assert.match(migration, /resolved_at/);
assert.match(source, /eq\("workspace_id", workspaceId\)/, "notification source queries are workspace-scoped");
assert.match(source, /approval_required/);
assert.match(source, /connector_attention/);
assert.match(source, /billing_attention/);
assert.match(source, /trial_ending/);
assert.match(source, /trial_expired/);
assert.match(source, /operator_paused/);
assert.match(source, /status: "resolved"/, "resolved source issues leave the active set");
assert.match(source, /!item\.dismissedAt && !item\.readAt/, "unread count only includes unresolved, undismissed work");
assert.doesNotMatch(source, /raw_payload|row\.message|email_body|encrypted_|prompt/i, "notification serialization excludes sensitive payloads");
assert.match(route, /getVerifiedSupabaseUser/);
assert.match(route, /resolveActiveWorkspaceId/);
assert.match(route, /requireWorkspaceMember/);
assert.match(route, /eq\("workspace_id", value\.workspaceId\)/, "mutations cannot target another workspace");
assert.match(route, /Critical notifications remain visible until resolved/);
assert.match(center, /Mark all read/);
assert.match(center, /You&apos;re all caught up/);
assert.match(center, /aria-label="Notifications"/);
assert.match(topbar, /NotificationCenter/);
assert.match(topbar, /unreadNotifications > 0/);
assert.doesNotMatch(navigation, /label: "Notifications"/, "notifications remain behind the bell, not in the sidebar");
assert.match(navigation, /label: "Activity"/);
assert.match(navigation, /label: "Execution logs"/);
console.log("Notification security, persistence, deduplication, and bell contracts passed.");
