/* eslint-disable @typescript-eslint/ban-ts-comment */
// The source-faithful tuple markup intentionally mirrors the static handoff data.
// @ts-nocheck
"use client";

import Link from "next/link";
import { useEffect } from "react";
import { appHref } from "@/lib/urls";
import OperatorsEditorial from "./operators-editorial";
import "./auterim-v3.css";

const DATA = {
  profile: [["Company", "Atlas Studio, professional services, 12 people", "Confirmed", "ok"], ["Systems of record", "Gmail and HubSpot carry client communication and pipeline", "Confirmed", "ok"], ["Customer journey", "Enquiry, proposal, onboarding, recurring delivery", "Inferred from website", "inf"], ["Repeated work", "Onboarding information is collected by hand for every client", "Inferred from tools", "inf"], ["Where work waits", "Lead replies queue behind one person's inbox", "Needs review", "rev"], ["Billing", "No billing system named. Left out of scope until you add one.", "Not provided", ""]],
  faq: [["What is an operator?", "A role with a defined scope, its own instructions and memory, the connectors its work requires, and a fixed approval boundary. It detects work, prepares it, waits at the gate, executes what you approve and logs the result."], ["How does Auterim know which operators I need?", "From your operating profile: website, industry, size, goals, tools and team structure. It looks for work that is delayed, missed or repeated by hand, and states the reason behind every recommendation."], ["Do I have to build workflows?", "No. Operators arrive with their role and workflows already defined, adapted to your profile. You adjust boundaries rather than designing anything from scratch."], ["Can an operator act without approval?", "Only where you have allowed it, such as reading messages or preparing drafts. Everything on the approval list waits for the named owner, and blocked actions never run."], ["Which tools connect today?", "Gmail, HubSpot, Google Calendar and Slack are available. Notion and Google Drive are in preview, Stripe is coming."], ["What if an operator lacks information?", "It stops and says so. Missing context is marked as not provided and the operator asks you instead of guessing."], ["Can I explore without connecting real data?", "Yes. Preview builds a profile from public information and shows recommendations and demo runs without touching a single system."]],
};

function Head({ label, title, body }: { label: string; title: string; body?: string }) { return <div className="head rv"><span className="lbl">{label}</span><div><h2>{title}</h2>{body && <p className="say">{body}</p>}</div></div>; }
function Mark() { return <span className="mk"><img src="/brand/auterim-mark-live.svg" width="16" height="16" alt="" />Auterim</span>; }

export default function V3Page() {
  useEffect(() => {
    const nodes = Array.from(document.querySelectorAll<HTMLElement>(".auterim-v3-page .rv"));
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduced || !("IntersectionObserver" in window)) {
      nodes.forEach((node) => node.classList.add("in"));
      return;
    }
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add("in");
        observer.unobserve(entry.target);
      }
    }), { threshold: 0.16 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  return <div className="auterim-v3-page">
    <section className="hero" id="top"><div className="glow" aria-hidden="true" /><div className="wrap hero-in"><a href="#run" className="pill"><span className="d" />Approvals before anything leaves your company</a><h1>The AI workforce built around how your company works.</h1><p className="say">Auterim learns your business, recommends the right operators, and lets them prepare and execute real work across your existing tools.</p><div className="hero-cta"><Link href={appHref("/app/onboarding")} className="btn btn-a">Start preview <span className="arrow">→</span></Link><a href="#how" className="btn btn-b">See how it works</a></div><span className="note">Begins with your website. Connect real tools when ready.</span><div className="proof"><div className="pf-top"><span className="pf-op">Revenue Operator</span><span className="pf-meta">Run 0142 · 09:44</span><span className="gate-tag">Approval required</span></div><div className="pf-body"><p>First reply to Northstar is drafted, qualified and waiting to send.</p><div className="gate-acts"><button className="mini go" type="button">Approve and send</button><button className="mini alt" type="button">Edit draft</button></div></div><div className="pf-bar"><i /></div></div></div></section>
    <div className="conns"><div className="wrap conns-in"><span className="lbl">Runs on the systems you already operate</span><div className="conns-set">{[["Gmail", "Available"], ["HubSpot", "Available"], ["Google Calendar", "Available"], ["Slack", "Available"], ["Notion", "Preview"], ["Google Drive", "Preview"], ["Stripe", "Soon"]].map(([name, state]) => <span key={name}>{name}<em>{state}</em></span>)}</div></div></div>
    <section className="sec" id="how"><div className="wrap"><Head label="The loop" title="Understand the company first. Recommend second. Execute last." body="Most AI tools hand you an empty canvas and wait for instructions. Auterim starts with your business." /><div className="body steps rv">{[["01", "Understand", "Your website, goals, tools, team and approval owner become one structured operating profile.", "Company profile"], ["02", "Recommend", "Auterim names the operators with the clearest path to value, and says exactly why each one fits.", "Recommended workforce"], ["03", "Execute", "Operators prepare work in your real systems, stop at every gate you set, and log what happened.", "Runs and approvals"]].map(([n, h, b, cue], i) => <div className={`step ${i === 0 ? "live" : ""}`} key={n}><span className="n">{n}</span><h3>{h}</h3><p>{b}</p><div className="cue"><span className="d" />{cue}</div></div>)}</div></div></section>
    <section className="sec" id="profile"><div className="wrap"><Head label="Company context" title="Auterim learns your business before it recommends anything." body="Your website, systems, processes, goals and approval structure become a reusable company profile every operator can work from." /><div className="body prof rv">{[DATA.profile.slice(0, 3), DATA.profile.slice(3)].map((column, i) => <div key={i}>{column.map(([k, v, status, tone]) => <div className="pr" key={k}><span className="k">{k}</span><span className="v">{v}<s className={tone}>{status}</s></span></div>)}</div>)}</div></div></section>
    <OperatorsEditorial />
    <section className="run" id="run"><div className="wrap"><Head label="One real run" title="One lead. One operator. One controlled run." body="Watch Auterim turn a real inbound signal into prepared work, and stop exactly where human approval is required." /><div className="trace rv"><div className="tr in"><div className="tr-k"><span className="sn">01</span>Input</div><div className="tr-s" /><div className="tr-c"><div className="src"><span>Website enquiry<em>Northstar, 09:41</em></span><span>CRM history<em>No prior contact</em></span><span>Company memory<em>Tone, offers, pricing</em></span></div></div></div><div className="tr work"><div className="tr-k"><span className="sn">02</span>Operator work</div><div className="tr-s" /><div className="tr-c">{["Detected a qualified inbound signal", "Qualified it against the ideal client profile", "Prepared a personalized first reply", "Updated the CRM record"].map((item) => <div className="wk" key={item}><span className="wn" /><span className="wt">{item}</span><em>09:43</em></div>)}</div></div><div className="tr gate"><div className="tr-k"><span className="sn">03</span><span className="gate-tag">Approval gate</span></div><div className="tr-s" /><div className="tr-c"><h3>Send the first reply to Sarah at Northstar?</h3><p>The draft, the CRM update and the follow-up are ready. First-contact messages wait for you.</p><div className="gate-acts"><button className="mini go" type="button">Approve and send</button><button className="mini alt" type="button">Edit draft</button><button className="mini alt" type="button">Reject</button></div><div className="gw">Owner: M. Keller, Managing Director · Policy: first contact, sales scope</div></div></div><div className="tr after"><div className="tr-k"><span className="sn">04</span>After approval</div><div className="tr-s" /><div className="tr-c">{["Send the reply via Gmail", "Create a three-day follow-up", "Log the outcome to company memory"].map((item) => <div className="wk" key={item}><span className="wn" /><span className="wt">{item}</span><em>Queued</em></div>)}</div></div></div></div></section>
    <section className="sec" id="policy"><div className="wrap"><Head label="Boundaries" title="Autonomy, with boundaries you control." body="Every operator has a defined scope. Some actions can run automatically, some stop for approval, and some are blocked entirely." /><div className="body pol rv">{[["a", "Can act", ["Read inbound messages", "Search the CRM", "Prepare replies", "Add internal notes"]], ["b", "Needs approval", ["Send external messages", "Change deal stages", "Offer discounts", "Contact new domains"]], ["c", "Never allowed", ["Delete CRM records", "Export customer databases", "Send bulk campaigns", "Change company policies"]]].map(([tone, title, items]) => <div className={`pcol ${tone}`} key={title as string}><div className="h">{title as string}</div><ul>{(items as string[]).map((item) => <li key={item}>{item}</li>)}</ul></div>)}</div><p className="pol-line rv">Revenue Operator <span>·</span> Sales scope <span>·</span> Approval owner: M. Keller</p></div></section>
    <section className="sec" id="arch"><div className="wrap"><Head label="Architecture" title="Auterim is the operating layer between your business and AI." body="Your existing systems remain the source of truth. Auterim adds the context, permissions, memory and controls AI needs to work safely across them." /><div className="body dia rv"><div className="dia-side left"><span className="dia-k">Your business</span>{["CRM", "Inbox", "Calendar", "Documents", "Support", "Billing"].map((x) => <div className="node" key={x}><span className="nt">{x}</span><span className="lead"><i /></span></div>)}<span className="dia-f">Source of truth</span></div><div className="mono"><div className="mono-h"><Mark /><span className="ms">Operating layer</span></div><div className="mono-b">{["Company profile", "Operators", "Memory", "Policies", "Approvals", "Activity history"].map((x) => <span key={x}>{x}</span>)}</div><div className="mono-f"><span className="gate-tag">Approval gate</span></div><div className="sweep" /></div><div className="dia-side right"><span className="dia-k">Intelligence</span>{["AI models", "Search", "Background tasks", "APIs", "Connected actions"].map((x) => <div className="node" key={x}><span className="lead"><i /></span><span className="nt">{x}</span></div>)}<span className="dia-f">Never touches your tools directly</span></div></div></div></section>
    <section className="sec"><div className="wrap"><Head label="Where it pays" title="Start with the work that keeps getting delayed." /><div className="body uc rv">{[["Lead response", "The enquiry waits in an inbox for someone with time.", "Enriched, qualified and drafted in minutes. One click sends it."], ["Client onboarding", "Details are chased by hand across email, docs and calls.", "The onboarding plan is prepared and every next step is coordinated."], ["Weekly operations", "Updates are assembled by hand from several systems.", "A written brief with blockers and next actions, every week."]].map(([h, before, after]) => <div className="ucr" key={h}><h3>{h}</h3><div className="b"><span className="k">Without Auterim</span>{before}</div><div className="a"><span className="k">With Auterim</span>{after}</div></div>)}</div></div></section>
    <section className="sec" id="pricing"><div className="wrap"><Head label="Getting started" title="Preview costs nothing and connects nothing." body="See your operating profile and recommended workforce first. Deploy against real systems only when you decide to. Pricing is announced at launch." /><div className="body plans rv">{[["Preview", "Free to explore", ["Operating profile from public information", "Recommended operators, with reasons", "Demo runs and approval flows", "No connectors, no real execution"]], ["Starter", "At launch", ["Two active operators", "Real connectors", "Company memory", "Approvals and activity log"]], ["Growth", "At launch", ["Six active operators", "Advanced policies", "Shared approvals", "Deeper company context"]], ["Enterprise", "Custom", ["High operator limits", "Custom policies and controls", "Dedicated environments", "Dedicated support"]]].map(([h, amount, items], i) => <div className={`pl ${i === 0 ? "now" : ""}`} key={h}><h3>{h}</h3><span className="amt">{amount}</span><ul>{(items as string[]).map((x) => <li key={x}>{x}</li>)}</ul>{i === 0 && <Link className="go" href={appHref("/app/onboarding")}>Start preview →</Link>}</div>)}</div></div></section>
    <section className="sec"><div className="wrap"><Head label="Questions" title="Answers, not positioning." /><div className="body faq rv">{DATA.faq.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
    <section className="close"><div className="wrap close-in"><span className="lbl">Start with your company</span><h2>See where AI can work before you connect anything.</h2><p>Build your operating profile, read the recommendations, and deploy the first operator when you are ready.</p><div className="hero-cta"><Link href={appHref("/app/onboarding")} className="btn btn-a">Start preview →</Link><a href="#operators" className="btn btn-b">See the operators</a></div></div></section>
    <footer className="foot"><div className="wrap"><div className="foot-grid"><div className="foot-brand"><a href="#top" className="mark"><Mark /></a><p>The operating layer between company context and AI execution.</p></div><div><h4>Platform</h4><ul><li><a href="#profile">Company profile</a></li><li><a href="#operators">Operators</a></li><li><a href="#run">Runs</a></li><li><a href="#policy">Approvals</a></li></ul></div><div><h4>Resources</h4><ul><li><a href="#pricing">Piloting</a></li><li><a href="#policy">Security</a></li><li><a href="#top">Documentation <i>Planned</i></a></li><li><a href="#top">Changelog <i>Planned</i></a></li></ul></div><div><h4>Company</h4><ul><li><a href="#top">About <i>Planned</i></a></li><li><a href="mailto:hello@auterim.com">Contact</a></li><li><Link href="/privacy">Privacy</Link></li><li><Link href="/terms">Terms</Link></li></ul></div></div><div className="foot-base"><span>© 2026 Auterim</span><span className="r">Interface examples show demo data, not customer activity.</span></div></div></footer>
  </div>;
}
