import type { PlannerPost } from "@/lib/supabase-server";

export type PlannerSeedPost = Omit<PlannerPost, "id" | "created_at" | "updated_at">;

export const PLANNER_SEED_POSTS: PlannerSeedPost[] = [
  {
    title: "SilentSpend case spotlight",
    week_label: "Week 18",
    template_type: "carousel",
    best_for: "linkedin",
    platforms: ["linkedin", "instagram"],
    recommended_format: "1:1 Square",
    format_variants: ["1:1 Square", "4:5 Portrait"],
    status: "ready",
    instagram_exported: true,
    instagram_posted: false,
    instagram_posted_at: null,
    facebook_exported: false,
    facebook_posted: false,
    facebook_posted_at: null,
    linkedin_exported: true,
    linkedin_posted: false,
    linkedin_posted_at: null,
    posted_at: null,
    notes:
      "Case angle around monetization intelligence and decision-layer execution.",
    social_asset_key: "w17-carousel-web",
  },
  {
    title: "Execution quality authority post",
    week_label: "Week 18",
    template_type: "authority",
    best_for: "linkedin",
    platforms: ["linkedin", "facebook"],
    recommended_format: "1:1 Square",
    format_variants: ["1:1 Square"],
    status: "draft",
    instagram_exported: false,
    instagram_posted: false,
    instagram_posted_at: null,
    facebook_exported: false,
    facebook_posted: false,
    facebook_posted_at: null,
    linkedin_exported: false,
    linkedin_posted: false,
    linkedin_posted_at: null,
    posted_at: null,
    notes:
      "Use this after publishing the SilentSpend case to reinforce operator-grade execution.",
    social_asset_key: "w17-authority-exec",
  },
  {
    title: "Shopify offer card",
    week_label: "Week 19",
    template_type: "offer",
    best_for: "instagram",
    platforms: ["instagram", "facebook"],
    recommended_format: "4:5 Portrait",
    format_variants: ["4:5 Portrait", "1:1 Square"],
    status: "posted",
    instagram_exported: true,
    instagram_posted: true,
    instagram_posted_at: new Date("2026-04-08T09:30:00.000Z").toISOString(),
    facebook_exported: true,
    facebook_posted: true,
    facebook_posted_at: new Date("2026-04-08T10:10:00.000Z").toISOString(),
    linkedin_exported: false,
    linkedin_posted: false,
    linkedin_posted_at: null,
    posted_at: new Date("2026-04-08T10:10:00.000Z").toISOString(),
    notes:
      "Use the same creative set for feed and retargeting. Keep copy direct and offer-led.",
    social_asset_key: "w18-offer-shopify",
  },
];
