import type { OSState, Agent, Workflow, Approval, MemoryEntry, Connector, ExecutionLog, Policy } from "@/lib/os/types";

// Deterministic IDs so seed is stable across reloads
export const SEED_AGENT_IDS = {
  rv: "agent-rv-001",
  mk: "agent-mk-002",
  cf: "agent-cf-003",
  op: "agent-op-004",
};

function ts(minutesAgo: number): string {
  const d = new Date(Date.now() - minutesAgo * 60 * 1000);
  return d.toISOString();
}

function timeStr(minutesAgo: number): string {
  const d = new Date(Date.now() - minutesAgo * 60 * 1000);
  return d.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit" });
}

export const SEED_AGENTS: Agent[] = [
  {
    id: SEED_AGENT_IDS.rv,
    name: "Revenue Operator",
    mark: "RV",
    color: "#4DE8E1",
    templateId: "revenue",
    status: "running",
    workspaceId: "ws-atlas",
    currentTask: "Drafting follow-ups for 14 leads in stage 2",
    deployedAt: ts(14 * 24 * 60),
    config: { tools: ["Gmail", "HubSpot", "Clearbit"], approvalPolicy: "require_approval", memoryScope: ["client", "brand"] },
    stats: { actionsThisWeek: 0, outputsThisWeek: 0, totalRuns: 0, metricLabel: "actions/wk", metricValue: "0" },
  },
  {
    id: SEED_AGENT_IDS.mk,
    name: "Marketing Operator",
    mark: "MK",
    color: "#A78BFA",
    templateId: "marketing",
    status: "running",
    workspaceId: "ws-atlas",
    currentTask: "Generating Q3 campaign brief from research notes",
    deployedAt: ts(21 * 24 * 60),
    config: { tools: ["Notion", "Search"], approvalPolicy: "require_approval", memoryScope: ["brand", "market"] },
    stats: { actionsThisWeek: 0, outputsThisWeek: 0, totalRuns: 0, metricLabel: "outputs/wk", metricValue: "0" },
  },
  {
    id: SEED_AGENT_IDS.cf,
    name: "Client Flow Operator",
    mark: "CF",
    color: "#5B8DEF",
    templateId: "client",
    status: "awaiting",
    workspaceId: "ws-atlas",
    currentTask: "Awaiting approval - new client kit (Northwind Co.)",
    deployedAt: ts(8 * 24 * 60),
    config: { tools: ["Notion", "Gmail", "Stripe"], approvalPolicy: "require_approval", memoryScope: ["client", "process"] },
    stats: { actionsThisWeek: 0, outputsThisWeek: 0, totalRuns: 0, metricLabel: "intakes/wk", metricValue: "0" },
  },
  {
    id: SEED_AGENT_IDS.op,
    name: "Operations Operator",
    mark: "OP",
    color: "#51D88A",
    templateId: "operations",
    status: "running",
    workspaceId: "ws-atlas",
    currentTask: "Compiling weekly summary across 6 channels",
    deployedAt: ts(30 * 24 * 60),
    config: { tools: ["Notion", "Slack", "Linear"], approvalPolicy: "allow", memoryScope: ["process", "market"] },
    stats: { actionsThisWeek: 0, outputsThisWeek: 0, totalRuns: 0, metricLabel: "saved/wk", metricValue: "0" },
  },
];

export const SEED_WORKFLOWS: Workflow[] = [
  { id: "wf-001", name: "Inbound revenue workflow", trigger: "Form submission", agentId: SEED_AGENT_IDS.rv, agentColor: "#4DE8E1", agentLabel: "Revenue", status: "active", totalRuns: 0, successRate: 0, avgDuration: "—", lastRun: "never", createdAt: ts(14 * 24 * 60) },
  { id: "wf-002", name: "Lead qualification", trigger: "CRM stage change", agentId: SEED_AGENT_IDS.rv, agentColor: "#4DE8E1", agentLabel: "Revenue", status: "active", totalRuns: 0, successRate: 0, avgDuration: "—", lastRun: "never", createdAt: ts(20 * 24 * 60) },
  { id: "wf-003", name: "Client onboarding kit", trigger: "New deal closed", agentId: SEED_AGENT_IDS.cf, agentColor: "#5B8DEF", agentLabel: "Client Flow", status: "active", totalRuns: 0, successRate: 0, avgDuration: "—", lastRun: "never", createdAt: ts(8 * 24 * 60) },
  { id: "wf-004", name: "Weekly operating digest", trigger: "Schedule · Mon 9AM", agentId: SEED_AGENT_IDS.op, agentColor: "#51D88A", agentLabel: "Operations", status: "active", totalRuns: 0, successRate: 0, avgDuration: "—", lastRun: "never", createdAt: ts(30 * 24 * 60) },
  { id: "wf-005", name: "Q3 SEO content pipeline", trigger: "Keyword batch upload", agentId: SEED_AGENT_IDS.mk, agentColor: "#A78BFA", agentLabel: "Marketing", status: "active", totalRuns: 0, successRate: 0, avgDuration: "—", lastRun: "never", createdAt: ts(21 * 24 * 60) },
  { id: "wf-006", name: "Outbound campaign launch", trigger: "Manual trigger", agentId: SEED_AGENT_IDS.mk, agentColor: "#A78BFA", agentLabel: "Marketing", status: "paused", totalRuns: 0, successRate: 0, avgDuration: "—", lastRun: "never", createdAt: ts(25 * 24 * 60) },
];

export const SEED_APPROVALS: Approval[] = [
  {
    id: "appr-001",
    type: "proposal",
    title: "Proposal - Northwind onboarding kit",
    body: "Draft includes pricing, SOW, kickoff checklist. Memory: Acme Industries (similar scope).",
    agentId: SEED_AGENT_IDS.cf,
    agentMark: "CF",
    agentColor: "#5B8DEF",
    runId: "run-seed-001",
    status: "pending",
    createdAt: ts(4),
  },
  {
    id: "appr-002",
    type: "follow-up",
    title: "Reply to Aiko Tanaka - intro thread",
    body: "Proposes Tue 2pm slot. Stage: intro to discovery. Includes 2 case studies.",
    agentId: SEED_AGENT_IDS.rv,
    agentMark: "RV",
    agentColor: "#4DE8E1",
    runId: "run-seed-002",
    status: "pending",
    createdAt: ts(11),
  },
  {
    id: "appr-003",
    type: "campaign",
    title: "Outbound launch - Q3 industry list",
    body: "320 contacts, 3 segments. Will pause if reply rate below 4% within 48h.",
    agentId: SEED_AGENT_IDS.mk,
    agentMark: "MK",
    agentColor: "#A78BFA",
    runId: "run-seed-003",
    status: "pending",
    createdAt: ts(28),
  },
];

export const SEED_MEMORY: MemoryEntry[] = [
  { id: "mem-001", type: "client", label: "Acme Industries", summary: "Enterprise Â· $184k deal", content: "B2B SaaS company, 280 employees. Key contact: Sarah Mills (COO). Preferred communication: email, formal tone. Signed 2 previous proposals. Response time typically 24h.", tags: ["crm", "proposal"], agentScope: [SEED_AGENT_IDS.rv, SEED_AGENT_IDS.cf], fieldCount: 14, updatedAt: ts(120) },
  { id: "mem-002", type: "client", label: "Northwind Co.", summary: "SMB Â· $28k deal active", content: "E-commerce brand, 45 employees. Key contact: James Northfield (CEO). Fast decision maker. Budget-conscious. Needs clear ROI framing. Currently in onboarding phase.", tags: ["crm", "onboarding"], agentScope: [SEED_AGENT_IDS.rv, SEED_AGENT_IDS.cf], fieldCount: 6, updatedAt: ts(4) },
  { id: "mem-003", type: "brand", label: "Brand voice guide", summary: "Tone, style, messaging rules", content: "Tone: premium, calm, confident. No hype, no agency swagger. Clear before clever. Use short, punchy sentences. Avoid em dashes. Active voice preferred. Never use leverage or synergy.", tags: ["content", "voice"], agentScope: [SEED_AGENT_IDS.rv, SEED_AGENT_IDS.mk, SEED_AGENT_IDS.cf], fieldCount: 22, updatedAt: ts(3 * 24 * 60) },
  { id: "mem-004", type: "process", label: "Proposal process", summary: "Discovery to close", content: "1. Discovery call. 2. Research audit (24h). 3. Proposal draft by Proposal Operator. 4. Internal review. 5. Client delivery. 6. Follow-up after 48h if no response.", tags: ["sales", "process"], agentScope: [SEED_AGENT_IDS.rv, SEED_AGENT_IDS.cf], fieldCount: 8, updatedAt: ts(7 * 24 * 60) },
  { id: "mem-005", type: "market", label: "Competitor landscape", summary: "Direct + indirect analysis", content: "Direct: Agency X, Studio Y, Firm Z. Key differentiators: we build, not manage. Premium tier, fixed scope, no retainers. Indirect: freelancers, no-code tools, internal hires.", tags: ["research", "market"], agentScope: [SEED_AGENT_IDS.mk], fieldCount: 11, updatedAt: ts(5 * 24 * 60) },
  { id: "mem-006", type: "product", label: "Service catalogue", summary: "Pricing + scope definitions", content: "Build: from $4,200. Systems: from $3,800. Growth: from $2,200/mo. All scoped, no open-ended retainers. Deposit: 50% upfront. Delivery: 4-8 weeks.", tags: ["product", "pricing"], agentScope: [SEED_AGENT_IDS.rv, SEED_AGENT_IDS.cf], fieldCount: 18, updatedAt: ts(2 * 24 * 60) },
];

export const SEED_CONNECTORS: Connector[] = [
  { id: "gmail", name: "Gmail", letter: "G", color: "#EA4335", category: "Communication", description: "Lead qualification and follow-up inbox actions.", status: "available", health: "disabled", lastSync: "-", syncMode: "realtime", syncFreq: "Real-time", permissions: ["Draft emails", "Send approved emails"], readScopes: ["Create email drafts", "Send approved emails"], writeScopes: [], approvalRequiredFor: ["External email send"], blockedActions: ["Delete email", "Read full inbox", "Change mailbox labels", "Send without approval"], operatorsAllowed: ["Revenue Operator", "Client Flow Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false, source: "seed" as const },
  { id: "slack", name: "Slack", letter: "Sl", color: "#A77FBC", category: "Communication", description: "Approval inbox and weekly operations digest channel delivery.", status: "available", health: "disabled", lastSync: "-", syncMode: "realtime", syncFreq: "Real-time", permissions: ["read", "write"], readScopes: ["channels.read", "messages.read"], writeScopes: ["messages.write", "reactions.write"], approvalRequiredFor: ["post_external_channel"], blockedActions: [], operatorsAllowed: ["Operations Operator", "Revenue Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false, source: "seed" as const },
  { id: "hubspot", name: "HubSpot", letter: "Hs", color: "#FF7A59", category: "CRM and sales", description: "CRM enrichment, stage updates and owner assignment.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 5 min", permissions: ["Read contacts", "Write contacts", "Read companies", "Write companies", "Read deals", "Write deals", "Read owners"], readScopes: ["Read contacts", "Read companies", "Read deals", "Read owners"], writeScopes: ["Write contacts", "Write companies", "Write deals"], approvalRequiredFor: ["Deal stage critical update", "External follow-up handoff"], blockedActions: ["Delete contacts", "Delete companies", "Delete deals"], operatorsAllowed: ["Revenue Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false, source: "seed" as const },
  { id: "notion", name: "Notion", letter: "N", color: "#ECEFF3", category: "Docs and knowledge", description: "Knowledge capture and structured operating notes.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 10 min", permissions: ["read", "write"], readScopes: ["pages.read", "databases.read"], writeScopes: ["pages.write", "databases.write"], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Operations Operator", "Marketing Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false, source: "seed" as const },
  { id: "google-calendar", name: "Google Calendar", letter: "GC", color: "#1A73E8", category: "Calendar and scheduling", description: "Scheduling assistant for client onboarding and sales meetings.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 5 min", permissions: ["read", "write"], readScopes: ["events.read"], writeScopes: ["events.write"], approvalRequiredFor: ["external_meeting_send"], blockedActions: [], operatorsAllowed: ["Client Flow Operator", "Revenue Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false, source: "seed" as const },
  { id: "stripe", name: "Stripe", letter: "St", color: "#635BFF", category: "Payments and commerce", description: "Payment and customer event handling for revenue reporting.", status: "available", health: "disabled", lastSync: "-", syncMode: "realtime", syncFreq: "Real-time", permissions: ["read"], readScopes: ["customers.read", "payments.read"], writeScopes: [], approvalRequiredFor: [], blockedActions: ["refund_create"], operatorsAllowed: ["Operations Operator", "Revenue Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false, source: "seed" as const },
  { id: "google-drive", name: "Google Drive", letter: "GD", color: "#34A853", category: "Docs and knowledge", description: "Content and SEO workflow document source.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 15 min", permissions: ["read", "write"], readScopes: ["files.read"], writeScopes: ["files.write"], approvalRequiredFor: ["external_share_link"], blockedActions: [], operatorsAllowed: ["Marketing Operator", "Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false, source: "seed" as const },
  { id: "outlook", name: "Outlook", letter: "O", color: "#0078D4", category: "Communication", description: "Enterprise inbox support for lead follow-up and support drafting.", status: "available", health: "disabled", lastSync: "-", syncMode: "manual", syncFreq: "Manual", permissions: ["read", "write", "send"], readScopes: ["mail.read"], writeScopes: ["mail.send"], approvalRequiredFor: ["send_external_email"], blockedActions: [], operatorsAllowed: ["Revenue Operator", "Support Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "salesforce", name: "Salesforce", letter: "SF", color: "#00A1E0", category: "CRM and sales", description: "Enterprise CRM sync for qualification, enrichment and forecasting.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 5 min", permissions: ["read", "write"], readScopes: ["leads.read", "opps.read"], writeScopes: ["leads.write", "opps.write"], approvalRequiredFor: ["pipeline_close_won"], blockedActions: ["record_delete"], operatorsAllowed: ["Revenue Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "shopify", name: "Shopify", letter: "Sh", color: "#95BF47", category: "Payments and commerce", description: "Order and customer event stream for commerce operations.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 5 min", permissions: ["read"], readScopes: ["orders.read", "customers.read"], writeScopes: [], approvalRequiredFor: [], blockedActions: ["order_cancel"], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "intercom", name: "Intercom", letter: "I", color: "#286EFA", category: "Support", description: "Support reply drafting and queue triage.", status: "available", health: "disabled", lastSync: "-", syncMode: "realtime", syncFreq: "Real-time", permissions: ["read", "write"], readScopes: ["tickets.read"], writeScopes: ["replies.write"], approvalRequiredFor: ["reply_send"], blockedActions: [], operatorsAllowed: ["Support Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "zendesk", name: "Zendesk", letter: "Z", color: "#03363D", category: "Support", description: "Support case updates and response assistance.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 10 min", permissions: ["read", "write"], readScopes: ["tickets.read"], writeScopes: ["tickets.write"], approvalRequiredFor: ["reply_send"], blockedActions: [], operatorsAllowed: ["Support Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "airtable", name: "Airtable", letter: "At", color: "#18BFFF", category: "CRM and sales", description: "Flexible CRM and ops database enrichment layer.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 10 min", permissions: ["read", "write"], readScopes: ["records.read"], writeScopes: ["records.write"], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "linear", name: "Linear", letter: "L", color: "#5E6AD2", category: "Work and project management", description: "Execution tracking for weekly operations digest workflows.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 2 min", permissions: ["read", "write"], readScopes: ["issues.read"], writeScopes: ["issues.write"], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "clickup", name: "ClickUp", letter: "CU", color: "#7B68EE", category: "Work and project management", description: "Project and task context for operator routing.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 5 min", permissions: ["read", "write"], readScopes: ["tasks.read"], writeScopes: ["tasks.write"], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "monday", name: "Monday", letter: "Mo", color: "#FF3D57", category: "Work and project management", description: "Planning board sync for operational workflows.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 5 min", permissions: ["read", "write"], readScopes: ["boards.read"], writeScopes: ["boards.write"], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "asana", name: "Asana", letter: "As", color: "#F06A6A", category: "Work and project management", description: "Project milestone source for weekly digest.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 5 min", permissions: ["read", "write"], readScopes: ["tasks.read"], writeScopes: ["tasks.write"], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "pipedrive", name: "Pipedrive", letter: "Pd", color: "#2C8E5A", category: "CRM and sales", description: "Pipeline management and revenue reporting source.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 5 min", permissions: ["read", "write"], readScopes: ["deals.read"], writeScopes: ["deals.write"], approvalRequiredFor: ["deal_close"], blockedActions: [], operatorsAllowed: ["Revenue Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "google-sheets", name: "Google Sheets", letter: "GS", color: "#0F9D58", category: "Docs and knowledge", description: "Reporting and revenue model updates.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 15 min", permissions: ["read", "write"], readScopes: ["sheets.read"], writeScopes: ["sheets.write"], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Operations Operator", "Revenue Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "calendly", name: "Calendly", letter: "Ca", color: "#006BFF", category: "Calendar and scheduling", description: "Inbound scheduling for lead qualification.", status: "available", health: "disabled", lastSync: "-", syncMode: "realtime", syncFreq: "Real-time", permissions: ["read"], readScopes: ["events.read"], writeScopes: [], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Revenue Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "zapier", name: "Zapier", letter: "Za", color: "#FF4A00", category: "Automation and custom", description: "Bridge automations for non-native tools.", status: "available", health: "disabled", lastSync: "-", syncMode: "manual", syncFreq: "Manual", permissions: ["read", "write"], readScopes: ["zaps.read"], writeScopes: ["hooks.write"], approvalRequiredFor: ["webhook_dispatch"], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "make", name: "Make", letter: "Mk", color: "#5A67D8", category: "Automation and custom", description: "Scenario execution for custom orchestration.", status: "available", health: "disabled", lastSync: "-", syncMode: "manual", syncFreq: "Manual", permissions: ["read", "write"], readScopes: ["scenarios.read"], writeScopes: ["scenarios.run"], approvalRequiredFor: ["scenario_execute_external"], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "n8n", name: "n8n", letter: "N8", color: "#EF4444", category: "Automation and custom", description: "Self-hosted automation runtime connector.", status: "available", health: "disabled", lastSync: "-", syncMode: "manual", syncFreq: "Manual", permissions: ["read", "write"], readScopes: ["workflows.read"], writeScopes: ["executions.run"], approvalRequiredFor: ["execution_dispatch_external"], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "webhooks", name: "Webhooks", letter: "Wh", color: "#22C55E", category: "Automation and custom", description: "Generic webhook triggers and event forwarding.", status: "available", health: "disabled", lastSync: "-", syncMode: "manual", syncFreq: "Manual", permissions: ["write"], readScopes: [], writeScopes: ["webhook.send"], approvalRequiredFor: ["external_webhook_send"], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "custom-api", name: "Custom API", letter: "API", color: "#14B8A6", category: "Automation and custom", description: "Custom REST integration endpoint for private systems.", status: "available", health: "disabled", lastSync: "-", syncMode: "manual", syncFreq: "Manual", permissions: ["read", "write"], readScopes: ["custom.read"], writeScopes: ["custom.write"], approvalRequiredFor: ["external_write"], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "outlook-calendar", name: "Outlook Calendar", letter: "OC", color: "#0A66C2", category: "Calendar and scheduling", description: "Microsoft scheduling source for onboarding and client ops.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 10 min", permissions: ["read", "write"], readScopes: ["calendar.read"], writeScopes: ["calendar.write"], approvalRequiredFor: ["external_meeting_send"], blockedActions: [], operatorsAllowed: ["Client Flow Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "teams", name: "Microsoft Teams", letter: "MT", color: "#6264A7", category: "Communication", description: "Approval and update broadcasting for Microsoft-first teams.", status: "available", health: "disabled", lastSync: "-", syncMode: "realtime", syncFreq: "Real-time", permissions: ["read", "write"], readScopes: ["channels.read"], writeScopes: ["messages.write"], approvalRequiredFor: ["post_external_channel"], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
  { id: "confluence", name: "Confluence", letter: "Cf", color: "#0052CC", category: "Docs and knowledge", description: "Knowledge base context for operator memory.", status: "available", health: "disabled", lastSync: "-", syncMode: "scheduled", syncFreq: "Every 15 min", permissions: ["read", "write"], readScopes: ["pages.read"], writeScopes: ["pages.write"], approvalRequiredFor: [], blockedActions: [], operatorsAllowed: ["Operations Operator"], records: "Not connected", lastSynced: "", eventsSynced: 0, authErrors: 0, recentSyncEvents: [], isConnected: false },
];

export const SEED_LOGS: ExecutionLog[] = [];

export const SEED_POLICIES: Policy[] = [
  {
    id: "pol-001",
    name: "Outbound communication gate",
    description: "External email sends require approval before execution.",
    enabled: true,
    category: "communication",
    actionType: "email.send",
    appliesToAgents: ["all"],
    appliesToConnectors: ["gmail", "outlook"],
    conditions: { externalRecipient: true },
    decision: "require_approval",
    reviewerRole: "admin",
    blockedReason: "",
    allowlist: [],
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(30),
    active: true,
  },
  {
    id: "pol-002",
    name: "CRM auto-write",
    description: "Revenue and client flow operators may update CRM records.",
    enabled: true,
    category: "crm",
    actionType: "crm.updateRecord",
    appliesToAgents: [SEED_AGENT_IDS.rv, SEED_AGENT_IDS.cf],
    appliesToConnectors: ["hubspot", "salesforce"],
    conditions: {},
    decision: "allow",
    reviewerRole: "admin",
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(25),
    active: true,
  },
  {
    id: "pol-003",
    name: "Delete CRM record blocked",
    description: "Destructive CRM deletes are blocked by execution guardrails.",
    enabled: true,
    category: "crm",
    actionType: "crm.deleteRecord",
    appliesToAgents: ["all"],
    appliesToConnectors: ["hubspot", "salesforce", "pipedrive"],
    conditions: { destructiveAction: true },
    decision: "block",
    blockedReason: "CRM delete is blocked in this workspace.",
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(24),
    active: true,
  },
  {
    id: "pol-004",
    name: "Pricing changes blocked",
    description: "Pricing updates are blocked from operator actions.",
    enabled: true,
    category: "pricing",
    actionType: "pricing.change",
    appliesToAgents: ["all"],
    appliesToConnectors: ["all"],
    conditions: { containsPricing: true },
    decision: "block",
    blockedReason: "Pricing changes require manual admin operations outside operators.",
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(23),
    active: true,
  },
  {
    id: "pol-005",
    name: "Payment refunds blocked",
    description: "Payment refunds are blocked from operator execution.",
    enabled: true,
    category: "payments",
    actionType: "payment.refund",
    appliesToAgents: ["all"],
    appliesToConnectors: ["stripe", "shopify"],
    conditions: { financialAction: true },
    decision: "block",
    blockedReason: "Refund actions are blocked by policy.",
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(22),
    active: true,
  },
  {
    id: "pol-006",
    name: "Memory write allowed",
    description: "Operators may write approved memory updates.",
    enabled: true,
    category: "memory",
    actionType: "memory.write",
    appliesToAgents: ["all"],
    appliesToConnectors: ["all"],
    conditions: {},
    decision: "allow",
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(21),
    active: true,
  },
  {
    id: "pol-007",
    name: "Memory delete requires admin approval",
    description: "Memory deletions require admin approval review.",
    enabled: true,
    category: "memory",
    actionType: "memory.delete",
    appliesToAgents: ["all"],
    appliesToConnectors: ["all"],
    conditions: { adminOnly: true, destructiveAction: true },
    decision: "require_approval",
    reviewerRole: "admin",
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(20),
    active: true,
  },
  {
    id: "pol-008",
    name: "External calendar invite gate",
    description: "External meeting invites require approval.",
    enabled: true,
    category: "calendar",
    actionType: "calendar.createExternalInvite",
    appliesToAgents: ["all"],
    appliesToConnectors: ["google-calendar", "outlook-calendar", "calendly"],
    conditions: { externalRecipient: true },
    decision: "require_approval",
    reviewerRole: "admin",
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(19),
    active: true,
  },
  {
    id: "pol-009",
    name: "External file sharing blocked",
    description: "External file sharing is blocked for customer-facing actions.",
    enabled: true,
    category: "files",
    actionType: "file.shareExternal",
    appliesToAgents: ["all"],
    appliesToConnectors: ["google-drive", "notion"],
    conditions: { customerFacing: true },
    decision: "block",
    blockedReason: "External file sharing is blocked by workspace guardrails.",
    createdAt: ts(60 * 24 * 30),
    updatedAt: ts(18),
    active: true,
  },
];

export const SEED_WORKSPACE = {
  id: "ws-atlas",
  name: "Workspace",
  environment: "setup",
  region: "eu-west-1",
  plan: "preview",
  planTier: "preview" as const,
  billingStatus: "preview" as const,
};

export const SEED_CURRENT_USER = {
  id: "usr-001",
  name: "Workspace Admin",
  email: "admin@workspace.com",
  roleLabel: "Admin",
  initials: "WA",
  notifications: {
    approvals: true,
    digest: true,
    alerts: true,
  },
};

export const SEED_TEAM_MEMBERS = [
  { id: "tm-001", name: "Workspace Admin", email: "admin@workspace.com", role: "Admin", initials: "WA", color: "#4DE8E1", access: ["All operators", "Approvals", "Settings"], status: "online" as const, active: true },
  { id: "tm-002", name: "Revenue Reviewer", email: "reviewer@inovense.com", role: "Operator - Reviewer", initials: "RR", color: "#A78BFA", access: ["Approvals", "Outputs"], status: "online" as const, active: true },
  { id: "tm-003", name: "Workflow Viewer", email: "viewer@inovense.com", role: "Operator - Viewer", initials: "WV", color: "#5B8DEF", access: ["Insights", "Outputs"], status: "offline" as const, active: true },
];

export const SEED_SETTINGS = {
  workspace: {
    name: "Atlas & Co.",
    environment: "production",
    region: "eu-west-1",
    plan: "preview",
  },
  approvalPolicy: {
    outboundComms: "Always require approval",
    proposals: "Always require approval",
    internalReports: "Auto-approve within policy",
    crmWrites: "Auto-approve",
  },
  notifications: {
    approvalInbox: "Slack - #revops + email",
    weeklyDigest: "Email - Monday 9AM",
    errorAlerts: "Slack - #ops-alerts",
    newAgentDeployed: "Email - all admins",
  },
};

export const SEED_DASHBOARD = {
  timeRange: "7d" as const,
  viewMode: "operator" as const,
};

export function buildSeedState(): OSState {
  return {
    onboarding: {
      isComplete: false,
      mainGoals: [],
      initialConnectors: [],
    },
    workspace: SEED_WORKSPACE,
    currentUser: SEED_CURRENT_USER,
    teamMembers: SEED_TEAM_MEMBERS,
    settings: SEED_SETTINGS,
    dashboard: SEED_DASHBOARD,
    agents: SEED_AGENTS,
    agentRuns: [],
    workflows: SEED_WORKFLOWS,
    approvals: SEED_APPROVALS,
    memory: SEED_MEMORY,
    connectors: SEED_CONNECTORS,
    logs: SEED_LOGS,
    policies: SEED_POLICIES,
  };
}
