import type { AgentTemplate } from "@/lib/os/types";

export const AGENT_TEMPLATES: Record<string, AgentTemplate> = {
  revenue: {
    id: "revenue",
    name: "Revenue Operator",
    mark: "RV",
    color: "#4DE8E1",
    role: "Sales · Pipeline",
    tag: "Sales · Pipeline",
    description: "Handles leads, follow-up, opportunity qualification and proposal angles. Connected to CRM, email, and enrichment tools.",
    allowedTools: ["Gmail (draft)", "HubSpot (read/write)", "Clearbit (read)", "Memory (read)", "Slack (read)"],
    allowedActions: [
      "read_crm",
      "write_crm",
      "enrich_lead",
      "read_memory",
      "draft_email",
      "qualify_lead",
      "update_opportunity_stage",
      "schedule_reminder",
    ],
    requiresApprovalFor: [
      "send_external_email",
      "create_proposal",
      "change_deal_value",
    ],
    blockedActions: [
      "delete_crm_record",
      "change_pricing",
      "access_billing",
    ],
    defaultPolicies: [
      { action: "send_external_email", effect: "require_approval" },
      { action: "create_proposal", effect: "require_approval" },
      { action: "draft_email", effect: "allow" },
      { action: "read_crm", effect: "allow" },
      { action: "write_crm", effect: "allow" },
      { action: "delete_crm_record", effect: "block" },
      { action: "change_pricing", effect: "block" },
    ],
    runSimulation: {
      steps: [
        { name: "Read memory", sub: "Client context + brand voice", logEvent: "memory_read", logMessage: "Read client context (8 fields) + brand voice guide (22 fields)", duration: "0.1s", logStatus: "ok" },
        { name: "Enrich lead", sub: "Clearbit + HubSpot", logEvent: "tool_call", logMessage: "Clearbit enrichment · Northwind Co. · 14 fields returned", duration: "1.8s", logStatus: "ok" },
        { name: "Qualify lead", sub: "ICP scoring", logEvent: "llm_call", logMessage: "Qualifying lead against ICP criteria · score 8.4/10 · stage: discovery", duration: "2.4s", logStatus: "ok" },
        { name: "Draft reply", sub: "Brand voice applied", logEvent: "llm_call", logMessage: "Generated follow-up email draft · 340 tokens · brand voice applied", duration: "4.2s", logStatus: "ok", requiresApproval: true },
        { name: "Await approval", sub: "Slack #revops", logEvent: "approval_requested", logMessage: "Requested approval for outbound email to Northwind Co.", duration: "-", logStatus: "waiting" },
      ],
      approvalType: "follow-up",
      approvalTitle: "Reply to Northwind Co. - inbound lead",
      approvalBody: "Qualification score 8.4/10. Stage: intro to discovery. Draft references 2 case studies. Tone: confident, warm. Ready to send via Gmail.",
    },
    sampleOutput: {
      type: "email_draft",
      title: "Follow-up · Northwind Co.",
      summary: "340-token follow-up referencing specific pain points, 2 case studies, and a proposed discovery call slot.",
    },
  },

  marketing: {
    id: "marketing",
    name: "Marketing Operator",
    mark: "MK",
    color: "#A78BFA",
    role: "Content · SEO",
    tag: "Content · SEO",
    description: "Handles content creation, ad angles, SEO briefs and campaign ideas. Publishes to Notion, schedules to social.",
    allowedTools: ["Notion (read/write)", "Memory (read)", "Search (read)", "Slack (read)"],
    allowedActions: [
      "read_memory",
      "search_web",
      "generate_brief",
      "publish_notion",
      "create_campaign",
      "draft_ad_copy",
      "analyze_keywords",
    ],
    requiresApprovalFor: [
      "launch_campaign",
      "publish_external",
      "send_external_email",
    ],
    blockedActions: [
      "access_billing",
      "delete_crm_record",
      "change_pricing",
    ],
    defaultPolicies: [
      { action: "launch_campaign", effect: "require_approval" },
      { action: "publish_external", effect: "require_approval" },
      { action: "generate_brief", effect: "allow" },
      { action: "publish_notion", effect: "allow" },
      { action: "analyze_keywords", effect: "allow" },
    ],
    runSimulation: {
      steps: [
        { name: "Read memory", sub: "Brand voice + content strategy", logEvent: "memory_read", logMessage: "Read brand voice guide (22 fields) + content strategy (8 fields)", duration: "0.1s", logStatus: "ok" },
        { name: "Keyword research", sub: "Search volume data", logEvent: "tool_call", logMessage: "Analysed 3 target keywords · volume, difficulty, competitor gap returned", duration: "2.2s", logStatus: "ok" },
        { name: "Generate brief", sub: "SEO angles + structure", logEvent: "llm_call", logMessage: "Generated Q3 SEO brief · 10 article angles across 3 clusters · 1,840 tokens", duration: "6.8s", logStatus: "ok" },
        { name: "Publish to Notion", sub: "Content workspace", logEvent: "tool_call", logMessage: "Published Q3 SEO brief to Notion · 1,420w · content/q3-seo-plan", duration: "0.8s", logStatus: "ok" },
        { name: "Log output", sub: "Execution record", logEvent: "output_published", logMessage: "SEO brief published · 1,420w · stored in Notion", duration: "0.1s", logStatus: "ok" },
      ],
    },
    sampleOutput: {
      type: "seo_brief",
      title: "Q3 SEO content plan",
      summary: "10 article angles across 3 clusters with search volumes, competitor gap, and priority ordering.",
      wordCount: 1420,
    },
  },

  client: {
    id: "client",
    name: "Client Flow Operator",
    mark: "CF",
    color: "#5B8DEF",
    role: "Intake · Onboarding",
    tag: "Intake · Onboarding",
    description: "Handles intake, onboarding kit creation, reminders and client updates. Generates proposals and SOW documents.",
    allowedTools: ["Notion (read/write)", "Memory (read/write)", "Gmail (draft)", "Stripe (read)", "Slack (read)"],
    allowedActions: [
      "read_memory",
      "write_memory",
      "create_onboarding_kit",
      "draft_proposal",
      "create_notion_doc",
      "schedule_reminder",
      "read_crm",
    ],
    requiresApprovalFor: [
      "send_proposal",
      "send_external_email",
      "send_onboarding_kit",
    ],
    blockedActions: [
      "charge_payment",
      "delete_crm_record",
      "change_pricing",
    ],
    defaultPolicies: [
      { action: "send_proposal", effect: "require_approval" },
      { action: "send_onboarding_kit", effect: "require_approval" },
      { action: "create_notion_doc", effect: "allow" },
      { action: "draft_proposal", effect: "allow" },
      { action: "charge_payment", effect: "block" },
    ],
    runSimulation: {
      steps: [
        { name: "Read memory", sub: "Client record · Northwind Co.", logEvent: "memory_read", logMessage: "Read client context: Northwind Co. (6 fields) + proposal template (12 fields)", duration: "0.1s", logStatus: "ok" },
        { name: "Generate kit", sub: "Onboarding package", logEvent: "llm_call", logMessage: "Generated onboarding kit · 12 pages · pricing, SOW, kickoff checklist", duration: "5.4s", logStatus: "ok" },
        { name: "Create document", sub: "Notion · client space", logEvent: "tool_call", logMessage: "Created Notion doc · client/northwind/onboarding-kit-v1", duration: "0.9s", logStatus: "ok", requiresApproval: true },
        { name: "Await approval", sub: "Review before sending", logEvent: "approval_requested", logMessage: "Requested approval to send onboarding kit to Northwind Co.", duration: "-", logStatus: "waiting" },
      ],
      approvalType: "proposal",
      approvalTitle: "Onboarding kit - Northwind Co.",
      approvalBody: "12-page kit including pricing ($28,400), SOW, kickoff checklist. Memory reference: Acme Industries (similar scope). Ready to send via email.",
    },
    sampleOutput: {
      type: "onboarding_kit",
      title: "Northwind Co. onboarding kit",
      summary: "12-page document covering pricing, SOW, kickoff checklist, and timeline.",
      wordCount: 1840,
    },
  },

  operations: {
    id: "operations",
    name: "Operations Operator",
    mark: "OP",
    color: "#51D88A",
    role: "Reports · Internal",
    tag: "Reports · Internal",
    description: "Handles internal summaries, reports, task coordination, and process documentation. Publishes digests to Slack and email.",
    allowedTools: ["Notion (read/write)", "Slack (read/write)", "Memory (read)", "Linear (read)", "Gmail (draft)"],
    allowedActions: [
      "read_memory",
      "read_crm",
      "generate_digest",
      "publish_notion",
      "schedule_digest",
      "post_slack",
      "create_task",
    ],
    requiresApprovalFor: [
      "send_external_email",
      "publish_external",
    ],
    blockedActions: [
      "delete_crm_record",
      "charge_payment",
      "change_pricing",
    ],
    defaultPolicies: [
      { action: "generate_digest", effect: "allow" },
      { action: "schedule_digest", effect: "allow" },
      { action: "post_slack", effect: "allow" },
      { action: "send_external_email", effect: "require_approval" },
    ],
    runSimulation: {
      steps: [
        { name: "Collect data", sub: "6 channels · CRM, Notion, Linear", logEvent: "memory_read", logMessage: "Collected weekly data from 6 channels: CRM, Notion, Linear, Slack, Gmail, Stripe", duration: "0.3s", logStatus: "ok" },
        { name: "Generate digest", sub: "Weekly summary", logEvent: "llm_call", logMessage: "Compiled weekly operating digest W21 · highlights: pipeline +18%, content +24%", duration: "3.8s", logStatus: "ok" },
        { name: "Schedule delivery", sub: "Monday 9AM · Slack + email", logEvent: "tool_call", logMessage: "Scheduled digest for Monday 09:00 AM · Slack #team + email digest list", duration: "0.4s", logStatus: "ok" },
        { name: "Log output", sub: "Execution complete", logEvent: "output_published", logMessage: "Weekly digest W21 scheduled · delivery: Monday 09:00 AM", duration: "0.1s", logStatus: "ok" },
      ],
    },
    sampleOutput: {
      type: "weekly_digest",
      title: "Weekly operating digest · W21",
      summary: "Pipeline +18%, content +24%, ops -1.4h. 3 stalled deals worth $96k flagged.",
      wordCount: 840,
    },
  },

  research: {
    id: "research",
    name: "Research Operator",
    mark: "RS",
    color: "#F5C26B",
    role: "Intelligence · Analysis",
    tag: "Intelligence · Analysis",
    description: "Conducts market, competitor, and prospect research. Produces structured intelligence briefs and enriches CRM records.",
    allowedTools: ["Search (read)", "Memory (read/write)", "Notion (write)", "HubSpot (read)"],
    allowedActions: [
      "search_web",
      "read_memory",
      "write_memory",
      "generate_brief",
      "enrich_lead",
      "publish_notion",
      "analyze_competitors",
    ],
    requiresApprovalFor: ["publish_external", "send_external_email"],
    blockedActions: ["delete_crm_record", "charge_payment", "change_pricing"],
    defaultPolicies: [
      { action: "generate_brief", effect: "allow" },
      { action: "publish_notion", effect: "allow" },
      { action: "search_web", effect: "allow" },
    ],
    runSimulation: {
      steps: [
        { name: "Load context", sub: "Memory + brief params", logEvent: "memory_read", logMessage: "Read market context (11 fields) + research brief template (6 fields)", duration: "0.1s", logStatus: "ok" },
        { name: "Web research", sub: "Competitor scan", logEvent: "tool_call", logMessage: "Scanned 12 competitor pages, 3 industry reports, 2 analyst summaries", duration: "4.1s", logStatus: "ok" },
        { name: "Synthesise brief", sub: "Structured output", logEvent: "llm_call", logMessage: "Generated research brief: 8 insights, 3 opportunity gaps, 2 threats identified", duration: "5.6s", logStatus: "ok" },
        { name: "Publish brief", sub: "Notion workspace", logEvent: "tool_call", logMessage: "Published intelligence brief to Notion - research/competitor-analysis-q3", duration: "0.6s", logStatus: "ok" },
        { name: "Log output", sub: "Execution complete", logEvent: "output_published", logMessage: "Research brief published - 1,280w - stored in Notion", duration: "0.1s", logStatus: "ok" },
      ],
    },
    sampleOutput: {
      type: "research_brief",
      title: "Competitor intelligence brief - Q3",
      summary: "8 insights across 3 direct competitors. 2 positioning gaps identified for targeting.",
      wordCount: 1280,
    },
  },

  proposal: {
    id: "proposal",
    name: "Proposal Operator",
    mark: "PR",
    color: "#F2767C",
    role: "Proposals · Scoping",
    tag: "Proposals · Scoping",
    description: "Generates scoped proposals, SOW documents and pricing packages from discovery notes and CRM data.",
    allowedTools: ["Memory (read)", "Notion (write)", "Gmail (draft)", "HubSpot (read)"],
    allowedActions: [
      "read_memory",
      "read_crm",
      "draft_proposal",
      "create_notion_doc",
      "generate_sow",
      "schedule_reminder",
    ],
    requiresApprovalFor: ["send_proposal", "send_external_email"],
    blockedActions: ["charge_payment", "delete_crm_record", "change_pricing"],
    defaultPolicies: [
      { action: "draft_proposal", effect: "allow" },
      { action: "create_notion_doc", effect: "allow" },
      { action: "send_proposal", effect: "require_approval" },
    ],
    runSimulation: {
      steps: [
        { name: "Read brief", sub: "Discovery notes + CRM", logEvent: "memory_read", logMessage: "Read discovery notes (8 fields) + service catalogue (18 fields) + client context (6 fields)", duration: "0.2s", logStatus: "ok" },
        { name: "Scope project", sub: "Deliverables + timeline", logEvent: "llm_call", logMessage: "Scoped project: 3 phases, 6 deliverables, 5-week timeline, $22,400 estimate", duration: "4.8s", logStatus: "ok" },
        { name: "Draft proposal", sub: "SOW + pricing", logEvent: "llm_call", logMessage: "Generated proposal draft - 14 pages, SOW, pricing table, kickoff checklist", duration: "6.2s", logStatus: "ok" },
        { name: "Create document", sub: "Notion - client space", logEvent: "tool_call", logMessage: "Created Notion doc - proposals/client-proposal-v1", duration: "0.7s", logStatus: "ok", requiresApproval: true },
        { name: "Await approval", sub: "Review before sending", logEvent: "approval_requested", logMessage: "Requested approval to send proposal to client", duration: "-", logStatus: "waiting" },
      ],
      approvalType: "proposal",
      approvalTitle: "Proposal ready for review",
      approvalBody: "14-page proposal with SOW, pricing ($22,400), and kickoff checklist. Scoped from discovery notes. Ready to send.",
    },
    sampleOutput: {
      type: "proposal",
      title: "Project proposal + SOW",
      summary: "14-page proposal with scoped deliverables, pricing, timeline, and kickoff checklist.",
      wordCount: 2100,
    },
  },

  finance: {
    id: "finance",
    name: "Finance Operator",
    mark: "FN",
    color: "#51D88A",
    role: "Invoicing · Revenue",
    tag: "Invoicing · Revenue",
    description: "Tracks invoices, monitors payment status, flags overdue accounts and compiles revenue reports from Stripe and CRM.",
    allowedTools: ["Stripe (read)", "HubSpot (read)", "Notion (write)", "Memory (read)", "Slack (read)"],
    allowedActions: [
      "read_crm",
      "read_memory",
      "monitor_payments",
      "generate_revenue_report",
      "flag_overdue",
      "publish_notion",
      "schedule_reminder",
    ],
    requiresApprovalFor: ["send_external_email", "publish_external"],
    blockedActions: ["charge_payment", "delete_crm_record", "change_pricing", "access_billing"],
    defaultPolicies: [
      { action: "monitor_payments", effect: "allow" },
      { action: "generate_revenue_report", effect: "allow" },
      { action: "publish_notion", effect: "allow" },
      { action: "charge_payment", effect: "block" },
    ],
    runSimulation: {
      steps: [
        { name: "Pull payments", sub: "Stripe - last 30 days", logEvent: "tool_call", logMessage: "Retrieved 48 payment records from Stripe - 30-day window", duration: "1.2s", logStatus: "ok" },
        { name: "Cross-reference CRM", sub: "Match to deals", logEvent: "tool_call", logMessage: "Matched 46 of 48 payments to HubSpot deals - 2 unmatched flagged", duration: "0.9s", logStatus: "ok" },
        { name: "Flag overdue", sub: "14+ day outstanding", logEvent: "llm_call", logMessage: "Identified 3 overdue invoices totalling $14,200 - flagged for follow-up", duration: "1.4s", logStatus: "warn" },
        { name: "Generate report", sub: "Revenue summary", logEvent: "output_published", logMessage: "Revenue report published - $128k collected, $14.2k overdue, 96.1% collection rate", duration: "0.8s", logStatus: "ok" },
      ],
    },
    sampleOutput: {
      type: "revenue_report",
      title: "Monthly revenue report",
      summary: "$128k collected. 3 overdue invoices ($14.2k). Collection rate 96.1%.",
    },
  },

  support: {
    id: "support",
    name: "Support Operator",
    mark: "SU",
    color: "#7EF6F0",
    role: "Client Success · Comms",
    tag: "Client Success · Comms",
    description: "Monitors client health, drafts responses to common queries, escalates urgent issues and logs support activity.",
    allowedTools: ["Gmail (read/draft)", "Slack (read)", "Memory (read/write)", "Notion (read)", "HubSpot (write)"],
    allowedActions: [
      "read_memory",
      "write_memory",
      "draft_email",
      "read_crm",
      "write_crm",
      "create_task",
      "schedule_reminder",
    ],
    requiresApprovalFor: ["send_external_email"],
    blockedActions: ["delete_crm_record", "charge_payment", "change_pricing"],
    defaultPolicies: [
      { action: "draft_email", effect: "allow" },
      { action: "read_crm", effect: "allow" },
      { action: "write_crm", effect: "allow" },
      { action: "send_external_email", effect: "require_approval" },
    ],
    runSimulation: {
      steps: [
        { name: "Scan inbox", sub: "New client messages", logEvent: "tool_call", logMessage: "Scanned inbox - 3 new client messages, 1 flagged urgent", duration: "0.8s", logStatus: "ok" },
        { name: "Load client context", sub: "CRM + memory", logEvent: "memory_read", logMessage: "Loaded context for 3 clients - history, tone, account status", duration: "0.2s", logStatus: "ok" },
        { name: "Draft replies", sub: "Brand voice applied", logEvent: "llm_call", logMessage: "Drafted 3 replies - 1 urgent escalation flagged for human review", duration: "3.8s", logStatus: "ok", requiresApproval: true },
        { name: "Await approval", sub: "Review before sending", logEvent: "approval_requested", logMessage: "Requested approval for client replies - 1 urgent flagged", duration: "-", logStatus: "waiting" },
      ],
      approvalType: "email",
      approvalTitle: "Client reply drafts - review required",
      approvalBody: "3 draft replies ready. 1 flagged urgent (Acme Industries - billing query). Tone reviewed against brand voice guide.",
    },
    sampleOutput: {
      type: "email_drafts",
      title: "Client reply drafts",
      summary: "3 drafts prepared. 1 urgent escalation flagged for review.",
    },
  },
};

export const TEMPLATE_LIST = Object.values(AGENT_TEMPLATES);
